import * as path from 'node:path';
import { defineConfig } from 'orval';

const infiniteOperationNames = [
  'FindMuscleGroups',
  'FindTrainings',
  'FindTrainingsForCalendar',
  'FindPerformanceStats',
  'FindNutritionIntakes',
];

export default defineConfig({
  'befit-mobile': {
    input: {
      target: './api/swagger.json',
      validation: false,
    },
    output: {
      mode: 'tags',
      target: './state/endpoints/api.ts',
      client: 'react-query',
      tslint: true,
      clean: true,
      override: {
        header: (info: any): string[] => [
          'Generated by orval 🍃',
          'Do not edit manually.',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
          '/* eslint-disable */',
          '// @ts-nocheck',
        ],
        enumGenerationType: 'enum',
        useTypeOverInterfaces: true,
        useDates: true,
        query: {
          useQuery: true,
          useSuspenseQuery: true,
          usePrefetch: false,
        },
        operations: infiniteOperationNames.reduce((acc: Record<string, any>, operation) => {
          acc[operation] = {
            query: {
              useQuery: true,
              useSuspenseQuery: true,
              useInfinite: true,
              useSuspenseInfiniteQuery: false,
              useInfiniteQueryParam: 'page',
            },
          };
          return acc;
        }, {}),
        mutator: {
          path: './api/api-client.ts',
          name: 'customInstance',
          alias: {
            '@/api/query-client': path.resolve(__dirname, './api/query-client'),
          },
        },
        contentType: {
          include: [
            'multipart/form-data',
            'application/json',
            'application/xml',
            'text/plain',
            'text/json',
          ],
        },
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write ./state/endpoints/**/*.ts',
    },
  },
});