/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
export type BestResultSummary = {
  maxWeight: Weight;
  repsAtMaxWeight?: number;
  achievedAt?: Date;
  maxReps?: number;
  weightAtMaxReps: Weight;
};

export type CreateMuscleGroupExerciseRequest = {
  muscleGroupId: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
};

export type CreateMuscleGroupExerciseResponse = {
  muscleGroupId: string;
  exerciseId: string;
};

export type CreateMuscleGroupRequest = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  type: MuscleGroupType;
};

export type CreateMuscleGroupResponse = {
  id: string;
};

export type CreateTrainingRequest = {
  trained: Date;
  /** @nullable */
  sets?: TrainingSetCommandDTO[] | null;
};

export type CreateTrainingResponse = {
  id?: string;
};

export type CreateTrainingSetRequest = {
  exerciseId: string;
  reps: number;
  weight: Weight;
  trainingId: string;
};

export type CreateTrainingSetResponse = {
  trainingId: string;
  trainingSetId: string;
};

export type ExerciseGroupDTO = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  muscleGroupName: string;
  exerciseSets: ExerciseSetDTO[];
};

export type ExerciseSetDTO = {
  id?: string;
  reps?: number;
  weight: Weight;
};

export type ExerciseSetsByDate = {
  date?: Date;
  /** @nullable */
  setsInfo?: SetHistory[] | null;
};

export type FindMuscleGroupExercisesResponse = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  /** @nullable */
  size?: string | null;
};

export type FindMuscleGroupExercisesResponsePagedResponse = {
  page: number;
  pageSize: number;
  pageCount: number;
  totalItemCount: number;
  items: FindMuscleGroupExercisesResponse[];
};

export type FindMuscleGroupsResponse = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  type: MuscleGroupType;
  exercises: MuscleGroupExerciseDTO[];
};

export type FindMuscleGroupsResponsePagedResponse = {
  page: number;
  pageSize: number;
  pageCount: number;
  totalItemCount: number;
  items: FindMuscleGroupsResponse[];
};

export type FindPerformanceStatisticsResponse = {
  sessionsDone: number;
  exercisesDone: number;
  muscleGroupsDone: number;
};

export type FindTrainingsForCalenderResponse = {
  trainings: TrainingDayDTO[];
};

export type FindTrainingsResponse = {
  id: string;
  trainedAt: Date;
  /** @minLength 1 */
  userId: string;
  /** @nullable */
  sets?: TrainingSetDTO[] | null;
};

export type FindTrainingsResponsePagedResponse = {
  page: number;
  pageSize: number;
  pageCount: number;
  totalItemCount: number;
  items: FindTrainingsResponse[];
};

export enum Gender {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
}
export type GetExerciseHistoryResponse = {
  exerciseId?: string;
  /** @nullable */
  exerciseName: string | null;
  lastWorkout?: LastWorkoutSummary;
  bestResult?: BestResultSummary;
  /** @nullable */
  sets?: ExerciseSetsByDate[] | null;
  /** @nullable */
  exerciseImageUrl?: string | null;
};

export type GetMuscleGroupByIdResponse = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  type: MuscleGroupType;
  exercises: MuscleGroupExerciseDTO[];
};

export type GetMuscleGroupExerciseByIdResponse = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  /** @nullable */
  size?: string | null;
};

export type GetTrainingByIdResponse = {
  id: string;
  trainedAt: Date;
  /** @minLength 1 */
  userId: string;
  /** @nullable */
  sets?: TrainingSetDTO[] | null;
};

export type GetUserBioResponse = {
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  nationality?: string | null;
  age?: number;
  height?: number;
  weight: Weight;
  gender?: Gender;
};

export type LastWorkoutSummary = {
  totalReps?: number;
  setCount?: number;
  weight: Weight;
  performedAt?: Date;
};

export type MuscleGroupExerciseDTO = {
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  /** @nullable */
  size?: string | null;
};

export enum MuscleGroupType {
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3,
}
export type ProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
};

export type SetHistory = {
  reps?: number;
  weight: Weight;
};

export type TrainingDayDTO = {
  trainedAtMonth: number;
  trainedAtDay: number;
  trainedAtYear: number;
  exercises: ExerciseGroupDTO[];
};

export type TrainingSetCommandDTO = {
  exerciseId: string;
  reps: number;
  weight: Weight;
};

export type TrainingSetDTO = {
  id: string;
  exerciseId: string;
  trainingId: string;
  reps: number;
  weight: Weight;
};

export type UpdateMuscleGroupRequest = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  imageUrl: string;
  type: MuscleGroupType;
  id: string;
};

export type UpdateMuscleGroupResponse = {
  id: string;
};

export type UpdateTrainingSetRequest = {
  exerciseId: string;
  reps: number;
  weight: Weight;
  trainingId: string;
};

export type UpdateTrainingSetResponse = {
  trainingId?: string;
  setId?: string;
};

export type UpdateUserBioRequest = {
  /** @nullable */
  clerkUserId: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  nationality: string | null;
  age?: number;
  height?: number;
  weight: Weight;
  gender?: Gender;
};

export type UpdateUserBioResponse = {
  isSuccess: boolean;
  /** @nullable */
  errorMessage: string | null;
};

/**
 * @nullable
 */
export type ValidationProblemDetailsErrors = { [key: string]: string[] } | null;

export type ValidationProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  errors?: ValidationProblemDetailsErrors;
  [key: string]: unknown;
};

export type Weight = {
  value?: number;
  /** @nullable */
  unit?: string | null;
};

export type FindMuscleGroupsParams = {
  includeExercises?: boolean;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  ascending?: boolean;
  all?: boolean;
};

export type FindMuscleGroupExercisesParams = {
  muscleGroupId?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  ascending?: boolean;
  all?: boolean;
};

export type FindPerformanceStatsParams = {
  timeInterval: string;
};

export type GetExerciseHistoryParams = {
  exerciseId: string;
  timeInterval: string;
};

export type FindTrainingsParams = {
  userId?: string;
  trainingId?: string;
  trainedAt?: Date;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  ascending?: boolean;
  all?: boolean;
};

export type FindTrainingsForCalendarParams = {
  userId: string;
  year?: number;
  month?: number;
};
