/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  GetUserBioResponse,
  ProblemDetails,
  UpdateUserBioRequest,
  UpdateUserBioResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const updateUserBio = (updateUserBioRequest: UpdateUserBioRequest) => {
  return customInstance<UpdateUserBioResponse>({
    url: `/api/auth/bio`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserBioRequest,
  });
};

export const getUpdateUserBioMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserBio>>,
    TError,
    { data: UpdateUserBioRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserBio>>,
  TError,
  { data: UpdateUserBioRequest },
  TContext
> => {
  const mutationKey = ["updateUserBio"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserBio>>,
    { data: UpdateUserBioRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateUserBio(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserBioMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserBio>>
>;
export type UpdateUserBioMutationBody = UpdateUserBioRequest;
export type UpdateUserBioMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useUpdateUserBio = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserBio>>,
      TError,
      { data: UpdateUserBioRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserBio>>,
  TError,
  { data: UpdateUserBioRequest },
  TContext
> => {
  const mutationOptions = getUpdateUserBioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getUsersBioInfo = (signal?: AbortSignal) => {
  return customInstance<GetUserBioResponse>({
    url: `/api/auth/bio`,
    method: "GET",
    signal,
  });
};

export const getGetUsersBioInfoQueryKey = () => {
  return [`/api/auth/bio`] as const;
};

export const getGetUsersBioInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUsersBioInfo>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersBioInfoQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersBioInfo>>> = ({
    signal,
  }) => getUsersBioInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUsersBioInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersBioInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersBioInfo>>
>;
export type GetUsersBioInfoQueryError = ProblemDetails;

export function useGetUsersBioInfo<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersBioInfo>>,
          TError,
          Awaited<ReturnType<typeof getUsersBioInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersBioInfo<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersBioInfo>>,
          TError,
          Awaited<ReturnType<typeof getUsersBioInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersBioInfo<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetUsersBioInfo<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersBioInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetUsersBioInfoSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getUsersBioInfo>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersBioInfoQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersBioInfo>>> = ({
    signal,
  }) => getUsersBioInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getUsersBioInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersBioInfoSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersBioInfo>>
>;
export type GetUsersBioInfoSuspenseQueryError = ProblemDetails;

export function useGetUsersBioInfoSuspense<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersBioInfoSuspense<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersBioInfoSuspense<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetUsersBioInfoSuspense<
  TData = Awaited<ReturnType<typeof getUsersBioInfo>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getUsersBioInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUsersBioInfoSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
