/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ProblemDetails,
  UpdateUserBioRequest,
  UpdateUserBioResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const updateUserBio = (updateUserBioRequest: UpdateUserBioRequest) => {
  return customInstance<UpdateUserBioResponse>({
    url: `/api/auth/bio`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserBioRequest,
  });
};

export const getUpdateUserBioMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserBio>>,
    TError,
    { data: UpdateUserBioRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserBio>>,
  TError,
  { data: UpdateUserBioRequest },
  TContext
> => {
  const mutationKey = ["updateUserBio"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserBio>>,
    { data: UpdateUserBioRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateUserBio(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserBioMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserBio>>
>;
export type UpdateUserBioMutationBody = UpdateUserBioRequest;
export type UpdateUserBioMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useUpdateUserBio = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserBio>>,
      TError,
      { data: UpdateUserBioRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserBio>>,
  TError,
  { data: UpdateUserBioRequest },
  TContext
> => {
  const mutationOptions = getUpdateUserBioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
