/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateMuscleGroupExerciseRequest,
  CreateMuscleGroupExerciseResponse,
  CreateMuscleGroupRequest,
  CreateMuscleGroupResponse,
  FindMuscleGroupExercisesParams,
  FindMuscleGroupExercisesResponsePagedResponse,
  FindMuscleGroupsParams,
  FindMuscleGroupsResponsePagedResponse,
  GetMuscleGroupByIdResponse,
  GetMuscleGroupExerciseByIdResponse,
  ProblemDetails,
  UpdateMuscleGroupRequest,
  UpdateMuscleGroupResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findMuscleGroups = (
  params?: FindMuscleGroupsParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindMuscleGroupsResponsePagedResponse>({
    url: `/api/muscle-groups`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindMuscleGroupsInfiniteQueryKey = (
  params?: FindMuscleGroupsParams,
) => {
  return [
    "infinate",
    `/api/muscle-groups`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFindMuscleGroupsQueryKey = (
  params?: FindMuscleGroupsParams,
) => {
  return [`/api/muscle-groups`, ...(params ? [params] : [])] as const;
};

export const getFindMuscleGroupsInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindMuscleGroupsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findMuscleGroups>>
  > = ({ signal, pageParam }) =>
    findMuscleGroups(
      { ...params, page: pageParam || params?.["page"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findMuscleGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindMuscleGroupsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findMuscleGroups>>
>;
export type FindMuscleGroupsInfiniteQueryError = ProblemDetails;

export function useFindMuscleGroupsInfinite<
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindMuscleGroupsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMuscleGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindMuscleGroupsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findMuscleGroups>>
  > = ({ signal }) => findMuscleGroups(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findMuscleGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindMuscleGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findMuscleGroups>>
>;
export type FindMuscleGroupsQueryError = ProblemDetails;

export function useFindMuscleGroups<
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindMuscleGroupsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMuscleGroupsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindMuscleGroupsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findMuscleGroups>>
  > = ({ signal }) => findMuscleGroups(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findMuscleGroups>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindMuscleGroupsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findMuscleGroups>>
>;
export type FindMuscleGroupsSuspenseQueryError = ProblemDetails;

export function useFindMuscleGroupsSuspense<
  TData = Awaited<ReturnType<typeof findMuscleGroups>>,
  TError = ProblemDetails,
>(
  params?: FindMuscleGroupsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroups>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindMuscleGroupsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createMuscleGroup = (
  createMuscleGroupRequest: CreateMuscleGroupRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateMuscleGroupResponse>({
    url: `/api/muscle-groups`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createMuscleGroupRequest,
    signal,
  });
};

export const getCreateMuscleGroupMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMuscleGroup>>,
    TError,
    { data: CreateMuscleGroupRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMuscleGroup>>,
  TError,
  { data: CreateMuscleGroupRequest },
  TContext
> => {
  const mutationKey = ["createMuscleGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMuscleGroup>>,
    { data: CreateMuscleGroupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createMuscleGroup(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMuscleGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMuscleGroup>>
>;
export type CreateMuscleGroupMutationBody = CreateMuscleGroupRequest;
export type CreateMuscleGroupMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateMuscleGroup = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMuscleGroup>>,
    TError,
    { data: CreateMuscleGroupRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createMuscleGroup>>,
  TError,
  { data: CreateMuscleGroupRequest },
  TContext
> => {
  const mutationOptions = getCreateMuscleGroupMutationOptions(options);

  return useMutation(mutationOptions);
};
export const updateMuscleGroup = (
  updateMuscleGroupRequest: UpdateMuscleGroupRequest,
) => {
  return customInstance<UpdateMuscleGroupResponse>({
    url: `/api/muscle-groups`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateMuscleGroupRequest,
  });
};

export const getUpdateMuscleGroupMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMuscleGroup>>,
    TError,
    { data: UpdateMuscleGroupRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMuscleGroup>>,
  TError,
  { data: UpdateMuscleGroupRequest },
  TContext
> => {
  const mutationKey = ["updateMuscleGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMuscleGroup>>,
    { data: UpdateMuscleGroupRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateMuscleGroup(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMuscleGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMuscleGroup>>
>;
export type UpdateMuscleGroupMutationBody = UpdateMuscleGroupRequest;
export type UpdateMuscleGroupMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useUpdateMuscleGroup = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMuscleGroup>>,
    TError,
    { data: UpdateMuscleGroupRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMuscleGroup>>,
  TError,
  { data: UpdateMuscleGroupRequest },
  TContext
> => {
  const mutationOptions = getUpdateMuscleGroupMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getMuscleGroupById = (id: string, signal?: AbortSignal) => {
  return customInstance<GetMuscleGroupByIdResponse>({
    url: `/api/muscle-groups/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetMuscleGroupByIdQueryKey = (id?: string) => {
  return [`/api/muscle-groups/${id}`] as const;
};

export const getGetMuscleGroupByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMuscleGroupById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMuscleGroupByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMuscleGroupById>>
  > = ({ signal }) => getMuscleGroupById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMuscleGroupById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMuscleGroupByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMuscleGroupById>>
>;
export type GetMuscleGroupByIdQueryError = ProblemDetails | ProblemDetails;

export function useGetMuscleGroupById<
  TData = Awaited<ReturnType<typeof getMuscleGroupById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupById>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMuscleGroupByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMuscleGroupByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMuscleGroupById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMuscleGroupByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMuscleGroupById>>
  > = ({ signal }) => getMuscleGroupById(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMuscleGroupById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMuscleGroupByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMuscleGroupById>>
>;
export type GetMuscleGroupByIdSuspenseQueryError =
  | ProblemDetails
  | ProblemDetails;

export function useGetMuscleGroupByIdSuspense<
  TData = Awaited<ReturnType<typeof getMuscleGroupById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupById>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMuscleGroupByIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteMuscleGroup = (id: string) => {
  return customInstance<unknown>({
    url: `/api/muscle-groups/${id}`,
    method: "DELETE",
  });
};

export const getDeleteMuscleGroupMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMuscleGroup>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMuscleGroup>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteMuscleGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMuscleGroup>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteMuscleGroup(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMuscleGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMuscleGroup>>
>;

export type DeleteMuscleGroupMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteMuscleGroup = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMuscleGroup>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteMuscleGroup>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteMuscleGroupMutationOptions(options);

  return useMutation(mutationOptions);
};
export const findMuscleGroupExercises = (
  id: string,
  params?: FindMuscleGroupExercisesParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindMuscleGroupExercisesResponsePagedResponse>({
    url: `/api/muscle-groups/${id}/exercises`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindMuscleGroupExercisesQueryKey = (
  id?: string,
  params?: FindMuscleGroupExercisesParams,
) => {
  return [
    `/api/muscle-groups/${id}/exercises`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFindMuscleGroupExercisesQueryOptions = <
  TData = Awaited<ReturnType<typeof findMuscleGroupExercises>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  params?: FindMuscleGroupExercisesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroupExercises>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindMuscleGroupExercisesQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findMuscleGroupExercises>>
  > = ({ signal }) => findMuscleGroupExercises(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof findMuscleGroupExercises>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindMuscleGroupExercisesQueryResult = NonNullable<
  Awaited<ReturnType<typeof findMuscleGroupExercises>>
>;
export type FindMuscleGroupExercisesQueryError =
  | ProblemDetails
  | ProblemDetails;

export function useFindMuscleGroupExercises<
  TData = Awaited<ReturnType<typeof findMuscleGroupExercises>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  params?: FindMuscleGroupExercisesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroupExercises>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindMuscleGroupExercisesQueryOptions(
    id,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMuscleGroupExercisesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findMuscleGroupExercises>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  params?: FindMuscleGroupExercisesParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroupExercises>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindMuscleGroupExercisesQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findMuscleGroupExercises>>
  > = ({ signal }) => findMuscleGroupExercises(id, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findMuscleGroupExercises>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindMuscleGroupExercisesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findMuscleGroupExercises>>
>;
export type FindMuscleGroupExercisesSuspenseQueryError =
  | ProblemDetails
  | ProblemDetails;

export function useFindMuscleGroupExercisesSuspense<
  TData = Awaited<ReturnType<typeof findMuscleGroupExercises>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  params?: FindMuscleGroupExercisesParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findMuscleGroupExercises>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindMuscleGroupExercisesSuspenseQueryOptions(
    id,
    params,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createMuscleGroupExercise = (
  id: string,
  createMuscleGroupExerciseRequest: CreateMuscleGroupExerciseRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateMuscleGroupExerciseResponse>({
    url: `/api/muscle-groups/${id}/exercises`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createMuscleGroupExerciseRequest,
    signal,
  });
};

export const getCreateMuscleGroupExerciseMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMuscleGroupExercise>>,
    TError,
    { id: string; data: CreateMuscleGroupExerciseRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMuscleGroupExercise>>,
  TError,
  { id: string; data: CreateMuscleGroupExerciseRequest },
  TContext
> => {
  const mutationKey = ["createMuscleGroupExercise"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMuscleGroupExercise>>,
    { id: string; data: CreateMuscleGroupExerciseRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return createMuscleGroupExercise(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMuscleGroupExerciseMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMuscleGroupExercise>>
>;
export type CreateMuscleGroupExerciseMutationBody =
  CreateMuscleGroupExerciseRequest;
export type CreateMuscleGroupExerciseMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateMuscleGroupExercise = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMuscleGroupExercise>>,
    TError,
    { id: string; data: CreateMuscleGroupExerciseRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createMuscleGroupExercise>>,
  TError,
  { id: string; data: CreateMuscleGroupExerciseRequest },
  TContext
> => {
  const mutationOptions = getCreateMuscleGroupExerciseMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getMuscleGroupExerciseById = (
  id: string,
  exerciseId: string,
  signal?: AbortSignal,
) => {
  return customInstance<GetMuscleGroupExerciseByIdResponse>({
    url: `/api/muscle-groups/${id}/exercises/${exerciseId}`,
    method: "GET",
    signal,
  });
};

export const getGetMuscleGroupExerciseByIdQueryKey = (
  id?: string,
  exerciseId?: string,
) => {
  return [`/api/muscle-groups/${id}/exercises/${exerciseId}`] as const;
};

export const getGetMuscleGroupExerciseByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  exerciseId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMuscleGroupExerciseByIdQueryKey(id, exerciseId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMuscleGroupExerciseById>>
  > = ({ signal }) => getMuscleGroupExerciseById(id, exerciseId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && exerciseId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMuscleGroupExerciseByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMuscleGroupExerciseById>>
>;
export type GetMuscleGroupExerciseByIdQueryError =
  | ProblemDetails
  | ProblemDetails;

export function useGetMuscleGroupExerciseById<
  TData = Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  exerciseId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMuscleGroupExerciseByIdQueryOptions(
    id,
    exerciseId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMuscleGroupExerciseByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  exerciseId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMuscleGroupExerciseByIdQueryKey(id, exerciseId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMuscleGroupExerciseById>>
  > = ({ signal }) => getMuscleGroupExerciseById(id, exerciseId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMuscleGroupExerciseByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMuscleGroupExerciseById>>
>;
export type GetMuscleGroupExerciseByIdSuspenseQueryError =
  | ProblemDetails
  | ProblemDetails;

export function useGetMuscleGroupExerciseByIdSuspense<
  TData = Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
  TError = ProblemDetails | ProblemDetails,
>(
  id: string,
  exerciseId: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getMuscleGroupExerciseById>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMuscleGroupExerciseByIdSuspenseQueryOptions(
    id,
    exerciseId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteMuscleGroupExercise = (id: string, exerciseId: string) => {
  return customInstance<unknown>({
    url: `/api/muscle-groups/${id}/exercises/${exerciseId}`,
    method: "DELETE",
  });
};

export const getDeleteMuscleGroupExerciseMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMuscleGroupExercise>>,
    TError,
    { id: string; exerciseId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMuscleGroupExercise>>,
  TError,
  { id: string; exerciseId: string },
  TContext
> => {
  const mutationKey = ["deleteMuscleGroupExercise"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMuscleGroupExercise>>,
    { id: string; exerciseId: string }
  > = (props) => {
    const { id, exerciseId } = props ?? {};

    return deleteMuscleGroupExercise(id, exerciseId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMuscleGroupExerciseMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMuscleGroupExercise>>
>;

export type DeleteMuscleGroupExerciseMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteMuscleGroupExercise = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMuscleGroupExercise>>,
    TError,
    { id: string; exerciseId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteMuscleGroupExercise>>,
  TError,
  { id: string; exerciseId: string },
  TContext
> => {
  const mutationOptions = getDeleteMuscleGroupExerciseMutationOptions(options);

  return useMutation(mutationOptions);
};
