/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateNutritionIntakeRequest,
  CreateNutritionIntakeResponse,
  FindNutritionIntakesParams,
  FindNutritionIntakesResponsePagedResponse,
  GetNutritionIntakeByIdResponse,
  UpdateNutritionIntakeRequest,
  UpdateNutritionIntakeResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findNutritionIntakes = (
  params?: FindNutritionIntakesParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindNutritionIntakesResponsePagedResponse>({
    url: `/api/nutrition-intakes`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindNutritionIntakesInfiniteQueryKey = (
  params?: FindNutritionIntakesParams,
) => {
  return [
    "infinate",
    `/api/nutrition-intakes`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFindNutritionIntakesQueryKey = (
  params?: FindNutritionIntakesParams,
) => {
  return [`/api/nutrition-intakes`, ...(params ? [params] : [])] as const;
};

export const getFindNutritionIntakesInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    FindNutritionIntakesParams["page"]
  >,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData,
        QueryKey,
        FindNutritionIntakesParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindNutritionIntakesInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    QueryKey,
    FindNutritionIntakesParams["page"]
  > = ({ signal, pageParam }) =>
    findNutritionIntakes(
      { ...params, page: pageParam || params?.["page"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    TError,
    TData,
    QueryKey,
    FindNutritionIntakesParams["page"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindNutritionIntakesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findNutritionIntakes>>
>;
export type FindNutritionIntakesInfiniteQueryError = unknown;

export function useFindNutritionIntakesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    FindNutritionIntakesParams["page"]
  >,
  TError = unknown,
>(
  params: undefined | FindNutritionIntakesParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData,
        QueryKey,
        FindNutritionIntakesParams["page"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          TError,
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          QueryKey
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    FindNutritionIntakesParams["page"]
  >,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData,
        QueryKey,
        FindNutritionIntakesParams["page"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          TError,
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          QueryKey
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    FindNutritionIntakesParams["page"]
  >,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData,
        QueryKey,
        FindNutritionIntakesParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindNutritionIntakesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    FindNutritionIntakesParams["page"]
  >,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData,
        QueryKey,
        FindNutritionIntakesParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindNutritionIntakesInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindNutritionIntakesQueryOptions = <
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindNutritionIntakesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findNutritionIntakes>>
  > = ({ signal }) => findNutritionIntakes(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindNutritionIntakesQueryResult = NonNullable<
  Awaited<ReturnType<typeof findNutritionIntakes>>
>;
export type FindNutritionIntakesQueryError = unknown;

export function useFindNutritionIntakes<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params: undefined | FindNutritionIntakesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          TError,
          Awaited<ReturnType<typeof findNutritionIntakes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakes<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findNutritionIntakes>>,
          TError,
          Awaited<ReturnType<typeof findNutritionIntakes>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakes<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindNutritionIntakes<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindNutritionIntakesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindNutritionIntakesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindNutritionIntakesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findNutritionIntakes>>
  > = ({ signal }) => findNutritionIntakes(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findNutritionIntakes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindNutritionIntakesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findNutritionIntakes>>
>;
export type FindNutritionIntakesSuspenseQueryError = unknown;

export function useFindNutritionIntakesSuspense<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params: undefined | FindNutritionIntakesParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakesSuspense<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindNutritionIntakesSuspense<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindNutritionIntakesSuspense<
  TData = Awaited<ReturnType<typeof findNutritionIntakes>>,
  TError = unknown,
>(
  params?: FindNutritionIntakesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findNutritionIntakes>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindNutritionIntakesSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createNutritionIntake = (
  createNutritionIntakeRequest: CreateNutritionIntakeRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateNutritionIntakeResponse>({
    url: `/api/nutrition-intakes`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createNutritionIntakeRequest,
    signal,
  });
};

export const getCreateNutritionIntakeMutationOptions = <
  TError = ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNutritionIntake>>,
    TError,
    { data: CreateNutritionIntakeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNutritionIntake>>,
  TError,
  { data: CreateNutritionIntakeRequest },
  TContext
> => {
  const mutationKey = ["createNutritionIntake"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNutritionIntake>>,
    { data: CreateNutritionIntakeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createNutritionIntake(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNutritionIntakeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createNutritionIntake>>
>;
export type CreateNutritionIntakeMutationBody = CreateNutritionIntakeRequest;
export type CreateNutritionIntakeMutationError = ValidationProblemDetails;

export const useCreateNutritionIntake = <
  TError = ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createNutritionIntake>>,
      TError,
      { data: CreateNutritionIntakeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createNutritionIntake>>,
  TError,
  { data: CreateNutritionIntakeRequest },
  TContext
> => {
  const mutationOptions = getCreateNutritionIntakeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getNutritionIntakeById = (id: string, signal?: AbortSignal) => {
  return customInstance<GetNutritionIntakeByIdResponse>({
    url: `/api/nutrition-intakes/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetNutritionIntakeByIdQueryKey = (id?: string) => {
  return [`/api/nutrition-intakes/${id}`] as const;
};

export const getGetNutritionIntakeByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNutritionIntakeByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNutritionIntakeById>>
  > = ({ signal }) => getNutritionIntakeById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNutritionIntakeById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNutritionIntakeByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNutritionIntakeById>>
>;
export type GetNutritionIntakeByIdQueryError = unknown;

export function useGetNutritionIntakeById<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNutritionIntakeById>>,
          TError,
          Awaited<ReturnType<typeof getNutritionIntakeById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNutritionIntakeById<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNutritionIntakeById>>,
          TError,
          Awaited<ReturnType<typeof getNutritionIntakeById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNutritionIntakeById<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetNutritionIntakeById<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNutritionIntakeByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetNutritionIntakeByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNutritionIntakeByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNutritionIntakeById>>
  > = ({ signal }) => getNutritionIntakeById(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getNutritionIntakeById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNutritionIntakeByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNutritionIntakeById>>
>;
export type GetNutritionIntakeByIdSuspenseQueryError = unknown;

export function useGetNutritionIntakeByIdSuspense<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNutritionIntakeByIdSuspense<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNutritionIntakeByIdSuspense<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetNutritionIntakeByIdSuspense<
  TData = Awaited<ReturnType<typeof getNutritionIntakeById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getNutritionIntakeById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNutritionIntakeByIdSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateNutritionIntake = (
  id: string,
  updateNutritionIntakeRequest: UpdateNutritionIntakeRequest,
) => {
  return customInstance<UpdateNutritionIntakeResponse>({
    url: `/api/nutrition-intakes/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateNutritionIntakeRequest,
  });
};

export const getUpdateNutritionIntakeMutationOptions = <
  TError = ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNutritionIntake>>,
    TError,
    { id: string; data: UpdateNutritionIntakeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNutritionIntake>>,
  TError,
  { id: string; data: UpdateNutritionIntakeRequest },
  TContext
> => {
  const mutationKey = ["updateNutritionIntake"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNutritionIntake>>,
    { id: string; data: UpdateNutritionIntakeRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateNutritionIntake(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNutritionIntakeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateNutritionIntake>>
>;
export type UpdateNutritionIntakeMutationBody = UpdateNutritionIntakeRequest;
export type UpdateNutritionIntakeMutationError = ValidationProblemDetails;

export const useUpdateNutritionIntake = <
  TError = ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateNutritionIntake>>,
      TError,
      { id: string; data: UpdateNutritionIntakeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateNutritionIntake>>,
  TError,
  { id: string; data: UpdateNutritionIntakeRequest },
  TContext
> => {
  const mutationOptions = getUpdateNutritionIntakeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteNutritionIntake = (id: string) => {
  return customInstance<void>({
    url: `/api/nutrition-intakes/${id}`,
    method: "DELETE",
  });
};

export const getDeleteNutritionIntakeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNutritionIntake>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNutritionIntake>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteNutritionIntake"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNutritionIntake>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteNutritionIntake(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNutritionIntakeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNutritionIntake>>
>;

export type DeleteNutritionIntakeMutationError = unknown;

export const useDeleteNutritionIntake = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteNutritionIntake>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteNutritionIntake>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteNutritionIntakeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
