/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";

import type {
  FindPerformanceStatisticsResponse,
  FindPerformanceStatsParams,
  GetExerciseHistoryParams,
  GetExerciseHistoryResponse,
  ProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findPerformanceStats = (
  params: FindPerformanceStatsParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindPerformanceStatisticsResponse>({
    url: `/api/stats`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindPerformanceStatsQueryKey = (
  params?: FindPerformanceStatsParams,
) => {
  return [`/api/stats`, ...(params ? [params] : [])] as const;
};

export const getFindPerformanceStatsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    FindPerformanceStatsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData,
        QueryKey,
        FindPerformanceStatsParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    QueryKey,
    FindPerformanceStatsParams["page"]
  > = ({ signal, pageParam }) =>
      findPerformanceStats(
        { ...params, page: pageParam || params?.["page"] },
        signal,
      );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData,
    QueryKey,
    FindPerformanceStatsParams["page"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindPerformanceStatsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsInfiniteQueryError = ProblemDetails;

export function useFindPerformanceStatsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    FindPerformanceStatsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData,
        QueryKey,
        FindPerformanceStatsParams["page"]
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        Awaited<ReturnType<typeof findPerformanceStats>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStatsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    FindPerformanceStatsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData,
        QueryKey,
        FindPerformanceStatsParams["page"]
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        Awaited<ReturnType<typeof findPerformanceStats>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStatsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    FindPerformanceStatsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData,
        QueryKey,
        FindPerformanceStatsParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindPerformanceStatsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    FindPerformanceStatsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData,
        QueryKey,
        FindPerformanceStatsParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindPerformanceStatsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindPerformanceStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>
  > = ({ signal }) => findPerformanceStats(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindPerformanceStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsQueryError = ProblemDetails;

export function useFindPerformanceStats<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        Awaited<ReturnType<typeof findPerformanceStats>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStats<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        Awaited<ReturnType<typeof findPerformanceStats>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStats<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindPerformanceStats<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindPerformanceStatsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindPerformanceStatsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>
  > = ({ signal }) => findPerformanceStats(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindPerformanceStatsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsSuspenseQueryError = ProblemDetails;

export function useFindPerformanceStatsSuspense<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStatsSuspense<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindPerformanceStatsSuspense<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindPerformanceStatsSuspense<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findPerformanceStats>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindPerformanceStatsSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getExerciseHistory = (
  exerciseId: string,
  params: GetExerciseHistoryParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetExerciseHistoryResponse>({
    url: `/api/stats/exercises/${exerciseId}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetExerciseHistoryQueryKey = (
  exerciseId?: string,
  params?: GetExerciseHistoryParams,
) => {
  return [
    `/api/stats/exercises/${exerciseId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetExerciseHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExerciseHistoryQueryKey(exerciseId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExerciseHistory>>
  > = ({ signal }) => getExerciseHistory(exerciseId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!exerciseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getExerciseHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetExerciseHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExerciseHistory>>
>;
export type GetExerciseHistoryQueryError = ProblemDetails;

export function useGetExerciseHistory<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        Awaited<ReturnType<typeof getExerciseHistory>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetExerciseHistory<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        Awaited<ReturnType<typeof getExerciseHistory>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetExerciseHistory<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetExerciseHistory<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetExerciseHistoryQueryOptions(
    exerciseId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetExerciseHistorySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExerciseHistoryQueryKey(exerciseId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExerciseHistory>>
  > = ({ signal }) => getExerciseHistory(exerciseId, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getExerciseHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetExerciseHistorySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExerciseHistory>>
>;
export type GetExerciseHistorySuspenseQueryError = ProblemDetails;

export function useGetExerciseHistorySuspense<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetExerciseHistorySuspense<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetExerciseHistorySuspense<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetExerciseHistorySuspense<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getExerciseHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetExerciseHistorySuspenseQueryOptions(
    exerciseId,
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
