/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  FindPerformanceStatisticsResponse,
  FindPerformanceStatsParams,
  GetExerciseHistoryParams,
  GetExerciseHistoryResponse,
  ProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findPerformanceStats = (
  params: FindPerformanceStatsParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindPerformanceStatisticsResponse>({
    url: `/api/stats`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindPerformanceStatsInfiniteQueryKey = (
  params?: FindPerformanceStatsParams,
) => {
  return ["infinate", `/api/stats`, ...(params ? [params] : [])] as const;
};

export const getFindPerformanceStatsQueryKey = (
  params?: FindPerformanceStatsParams,
) => {
  return [`/api/stats`, ...(params ? [params] : [])] as const;
};

export const getFindPerformanceStatsInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>
  > = ({ signal, pageParam }) =>
    findPerformanceStats(
      { ...params, page: pageParam || params?.["page"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindPerformanceStatsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsInfiniteQueryError = ProblemDetails;

export function useFindPerformanceStatsInfinite<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindPerformanceStatsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindPerformanceStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>
  > = ({ signal }) => findPerformanceStats(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindPerformanceStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsQueryError = ProblemDetails;

export function useFindPerformanceStats<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindPerformanceStatsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindPerformanceStatsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindPerformanceStatsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findPerformanceStats>>
  > = ({ signal }) => findPerformanceStats(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findPerformanceStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindPerformanceStatsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findPerformanceStats>>
>;
export type FindPerformanceStatsSuspenseQueryError = ProblemDetails;

export function useFindPerformanceStatsSuspense<
  TData = Awaited<ReturnType<typeof findPerformanceStats>>,
  TError = ProblemDetails,
>(
  params: FindPerformanceStatsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findPerformanceStats>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindPerformanceStatsSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getExerciseHistory = (
  exerciseId: string,
  params: GetExerciseHistoryParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetExerciseHistoryResponse>({
    url: `/api/stats/exercises/${exerciseId}`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetExerciseHistoryQueryKey = (
  exerciseId?: string,
  params?: GetExerciseHistoryParams,
) => {
  return [
    `/api/stats/exercises/${exerciseId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetExerciseHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getExerciseHistory>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExerciseHistoryQueryKey(exerciseId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExerciseHistory>>
  > = ({ signal }) => getExerciseHistory(exerciseId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!exerciseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getExerciseHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetExerciseHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExerciseHistory>>
>;
export type GetExerciseHistoryQueryError = ProblemDetails;

export function useGetExerciseHistory<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getExerciseHistory>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetExerciseHistoryQueryOptions(
    exerciseId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetExerciseHistorySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getExerciseHistory>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExerciseHistoryQueryKey(exerciseId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExerciseHistory>>
  > = ({ signal }) => getExerciseHistory(exerciseId, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getExerciseHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetExerciseHistorySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExerciseHistory>>
>;
export type GetExerciseHistorySuspenseQueryError = ProblemDetails;

export function useGetExerciseHistorySuspense<
  TData = Awaited<ReturnType<typeof getExerciseHistory>>,
  TError = ProblemDetails,
>(
  exerciseId: string,
  params: GetExerciseHistoryParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getExerciseHistory>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetExerciseHistorySuspenseQueryOptions(
    exerciseId,
    params,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
