/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateTrainingRequest,
  CreateTrainingResponse,
  CreateTrainingSetRequest,
  CreateTrainingSetResponse,
  FindTrainingsForCalendarParams,
  FindTrainingsForCalenderResponse,
  FindTrainingsParams,
  FindTrainingsResponsePagedResponse,
  GetTrainingByIdResponse,
  ProblemDetails,
  UpdateTrainingSetRequest,
  UpdateTrainingSetResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findTrainings = (
  params?: FindTrainingsParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindTrainingsResponsePagedResponse>({
    url: `/api/trainings`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindTrainingsInfiniteQueryKey = (
  params?: FindTrainingsParams,
) => {
  return ["infinate", `/api/trainings`, ...(params ? [params] : [])] as const;
};

export const getFindTrainingsQueryKey = (params?: FindTrainingsParams) => {
  return [`/api/trainings`, ...(params ? [params] : [])] as const;
};

export const getFindTrainingsInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTrainings>>> = ({
    signal,
    pageParam,
  }) =>
    findTrainings({ ...params, page: pageParam || params?.["page"] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsInfiniteQueryError = ProblemDetails;

export function useFindTrainingsInfinite<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindTrainingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTrainings>>> = ({
    signal,
  }) => findTrainings(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsQueryError = ProblemDetails;

export function useFindTrainings<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindTrainingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTrainings>>> = ({
    signal,
  }) => findTrainings(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsSuspenseQueryError = ProblemDetails;

export function useFindTrainingsSuspense<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findTrainings>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTraining = (
  createTrainingRequest: CreateTrainingRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateTrainingResponse>({
    url: `/api/trainings`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTrainingRequest,
    signal,
  });
};

export const getCreateTrainingMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTraining>>,
    TError,
    { data: CreateTrainingRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTraining>>,
  TError,
  { data: CreateTrainingRequest },
  TContext
> => {
  const mutationKey = ["createTraining"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTraining>>,
    { data: CreateTrainingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createTraining(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTrainingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTraining>>
>;
export type CreateTrainingMutationBody = CreateTrainingRequest;
export type CreateTrainingMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateTraining = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTraining>>,
    TError,
    { data: CreateTrainingRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTraining>>,
  TError,
  { data: CreateTrainingRequest },
  TContext
> => {
  const mutationOptions = getCreateTrainingMutationOptions(options);

  return useMutation(mutationOptions);
};
export const getTrainingById = (id: string, signal?: AbortSignal) => {
  return customInstance<GetTrainingByIdResponse>({
    url: `/api/trainings/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetTrainingByIdQueryKey = (id?: string) => {
  return [`/api/trainings/${id}`] as const;
};

export const getGetTrainingByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTrainingById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTrainingByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrainingById>>> = ({
    signal,
  }) => getTrainingById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrainingById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTrainingByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrainingById>>
>;
export type GetTrainingByIdQueryError = ProblemDetails;

export function useGetTrainingById<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTrainingById>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTrainingByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetTrainingByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getTrainingById>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTrainingByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrainingById>>> = ({
    signal,
  }) => getTrainingById(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getTrainingById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTrainingByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrainingById>>
>;
export type GetTrainingByIdSuspenseQueryError = ProblemDetails;

export function useGetTrainingByIdSuspense<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getTrainingById>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTrainingByIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteTraining = (id: string) => {
  return customInstance<unknown>({
    url: `/api/trainings/${id}`,
    method: "DELETE",
  });
};

export const getDeleteTrainingMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTraining>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTraining>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteTraining"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTraining>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTraining(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTrainingMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTraining>>
>;

export type DeleteTrainingMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteTraining = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTraining>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteTraining>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteTrainingMutationOptions(options);

  return useMutation(mutationOptions);
};
export const findTrainingsForCalendar = (
  params: FindTrainingsForCalendarParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindTrainingsForCalenderResponse>({
    url: `/api/trainings/Calendar`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindTrainingsForCalendarInfiniteQueryKey = (
  params?: FindTrainingsForCalendarParams,
) => {
  return [
    "infinate",
    `/api/trainings/Calendar`,
    ...(params ? [params] : []),
  ] as const;
};

export const getFindTrainingsForCalendarQueryKey = (
  params?: FindTrainingsForCalendarParams,
) => {
  return [`/api/trainings/Calendar`, ...(params ? [params] : [])] as const;
};

export const getFindTrainingsForCalendarInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFindTrainingsForCalendarInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>
  > = ({ signal, pageParam }) =>
    findTrainingsForCalendar(
      { ...params, page: pageParam || params?.["page"] },
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsForCalendarInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarInfiniteQueryError = ProblemDetails;

export function useFindTrainingsForCalendarInfinite<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsForCalendarInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsForCalendarQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsForCalendarQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>
  > = ({ signal }) => findTrainingsForCalendar(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsForCalendarQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarQueryError = ProblemDetails;

export function useFindTrainingsForCalendar<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsForCalendarQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsForCalendarSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsForCalendarQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>
  > = ({ signal }) => findTrainingsForCalendar(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FindTrainingsForCalendarSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarSuspenseQueryError = ProblemDetails;

export function useFindTrainingsForCalendarSuspense<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof findTrainingsForCalendar>>,
      TError,
      TData
    >;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindTrainingsForCalendarSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTrainingSet = (
  id: string,
  createTrainingSetRequest: CreateTrainingSetRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateTrainingSetResponse>({
    url: `/api/trainings/${id}/sets`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTrainingSetRequest,
    signal,
  });
};

export const getCreateTrainingSetMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTrainingSet>>,
    TError,
    { id: string; data: CreateTrainingSetRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTrainingSet>>,
  TError,
  { id: string; data: CreateTrainingSetRequest },
  TContext
> => {
  const mutationKey = ["createTrainingSet"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTrainingSet>>,
    { id: string; data: CreateTrainingSetRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return createTrainingSet(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTrainingSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTrainingSet>>
>;
export type CreateTrainingSetMutationBody = CreateTrainingSetRequest;
export type CreateTrainingSetMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateTrainingSet = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTrainingSet>>,
    TError,
    { id: string; data: CreateTrainingSetRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTrainingSet>>,
  TError,
  { id: string; data: CreateTrainingSetRequest },
  TContext
> => {
  const mutationOptions = getCreateTrainingSetMutationOptions(options);

  return useMutation(mutationOptions);
};
export const updateTrainingSet = (
  id: string,
  updateTrainingSetRequest: UpdateTrainingSetRequest,
) => {
  return customInstance<UpdateTrainingSetResponse>({
    url: `/api/trainings/${id}/sets`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateTrainingSetRequest,
  });
};

export const getUpdateTrainingSetMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTrainingSet>>,
    TError,
    { id: string; data: UpdateTrainingSetRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTrainingSet>>,
  TError,
  { id: string; data: UpdateTrainingSetRequest },
  TContext
> => {
  const mutationKey = ["updateTrainingSet"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTrainingSet>>,
    { id: string; data: UpdateTrainingSetRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTrainingSet(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTrainingSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTrainingSet>>
>;
export type UpdateTrainingSetMutationBody = UpdateTrainingSetRequest;
export type UpdateTrainingSetMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useUpdateTrainingSet = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTrainingSet>>,
    TError,
    { id: string; data: UpdateTrainingSetRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateTrainingSet>>,
  TError,
  { id: string; data: UpdateTrainingSetRequest },
  TContext
> => {
  const mutationOptions = getUpdateTrainingSetMutationOptions(options);

  return useMutation(mutationOptions);
};
export const deleteApiTrainingsIdSetsSetId = (id: string, setId: string) => {
  return customInstance<unknown>({
    url: `/api/trainings/${id}/sets/${setId}`,
    method: "DELETE",
  });
};

export const getDeleteApiTrainingsIdSetsSetIdMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
    TError,
    { id: string; setId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
  TError,
  { id: string; setId: string },
  TContext
> => {
  const mutationKey = ["deleteApiTrainingsIdSetsSetId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
    { id: string; setId: string }
  > = (props) => {
    const { id, setId } = props ?? {};

    return deleteApiTrainingsIdSetsSetId(id, setId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiTrainingsIdSetsSetIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>
>;

export type DeleteApiTrainingsIdSetsSetIdMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteApiTrainingsIdSetsSetId = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
    TError,
    { id: string; setId: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
  TError,
  { id: string; setId: string },
  TContext
> => {
  const mutationOptions =
    getDeleteApiTrainingsIdSetsSetIdMutationOptions(options);

  return useMutation(mutationOptions);
};
