/* /* eslint-disable *\/ */
/**
 * Generated by orval 🍃
 * Do not edit manually.
 * BeFit API
 * OpenAPI spec version: v1
 * // @ts-nocheck
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";

import type {
  CreateTrainingRequest,
  CreateTrainingResponse,
  CreateTrainingSetRequest,
  CreateTrainingSetResponse,
  FindTrainingsForCalendarParams,
  FindTrainingsForCalenderResponse,
  FindTrainingsParams,
  FindTrainingsResponsePagedResponse,
  GetTrainingByIdResponse,
  ProblemDetails,
  UpdateTrainingSetRequest,
  UpdateTrainingSetResponse,
  ValidationProblemDetails,
} from "./api.schemas";

import { customInstance } from "../../api/api-client";

export const findTrainings = (
  params?: FindTrainingsParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindTrainingsResponsePagedResponse>({
    url: `/api/trainings`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindTrainingsQueryKey = (params?: FindTrainingsParams) => {
  return [`/api/trainings`, ...(params ? [params] : [])] as const;
};

export const getFindTrainingsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainings>>,
    FindTrainingsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindTrainingsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainings>>,
    QueryKey,
    FindTrainingsParams["page"]
  > = ({ signal, pageParam }) =>
      findTrainings({ ...params, page: pageParam || params?.["page"] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData,
    QueryKey,
    FindTrainingsParams["page"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsInfiniteQueryError = ProblemDetails;

export function useFindTrainingsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainings>>,
    FindTrainingsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: undefined | FindTrainingsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsParams["page"]
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        Awaited<ReturnType<typeof findTrainings>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainings>>,
    FindTrainingsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsParams["page"]
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        Awaited<ReturnType<typeof findTrainings>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainings>>,
    FindTrainingsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainingsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainings>>,
    FindTrainingsParams["page"]
  >,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findTrainings>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindTrainingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTrainings>>> = ({
    signal,
  }) => findTrainings(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsQueryError = ProblemDetails;

export function useFindTrainings<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params: undefined | FindTrainingsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findTrainings>>, TError, TData>
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        Awaited<ReturnType<typeof findTrainings>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainings<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findTrainings>>, TError, TData>
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        Awaited<ReturnType<typeof findTrainings>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainings<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findTrainings>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainings<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findTrainings>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindTrainingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTrainings>>> = ({
    signal,
  }) => findTrainings(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findTrainings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainings>>
>;
export type FindTrainingsSuspenseQueryError = ProblemDetails;

export function useFindTrainingsSuspense<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params: undefined | FindTrainingsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsSuspense<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsSuspense<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainingsSuspense<
  TData = Awaited<ReturnType<typeof findTrainings>>,
  TError = ProblemDetails,
>(
  params?: FindTrainingsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainings>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTraining = (
  createTrainingRequest: CreateTrainingRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateTrainingResponse>({
    url: `/api/trainings`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTrainingRequest,
    signal,
  });
};

export const getCreateTrainingMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTraining>>,
    TError,
    { data: CreateTrainingRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTraining>>,
  TError,
  { data: CreateTrainingRequest },
  TContext
> => {
  const mutationKey = ["createTraining"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTraining>>,
    { data: CreateTrainingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createTraining(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTrainingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTraining>>
>;
export type CreateTrainingMutationBody = CreateTrainingRequest;
export type CreateTrainingMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateTraining = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTraining>>,
      TError,
      { data: CreateTrainingRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTraining>>,
  TError,
  { data: CreateTrainingRequest },
  TContext
> => {
  const mutationOptions = getCreateTrainingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getTrainingById = (id: string, signal?: AbortSignal) => {
  return customInstance<GetTrainingByIdResponse>({
    url: `/api/trainings/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetTrainingByIdQueryKey = (id?: string) => {
  return [`/api/trainings/${id}`] as const;
};

export const getGetTrainingByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTrainingByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrainingById>>> = ({
    signal,
  }) => getTrainingById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrainingById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTrainingByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrainingById>>
>;
export type GetTrainingByIdQueryError = ProblemDetails;

export function useGetTrainingById<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        Awaited<ReturnType<typeof getTrainingById>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrainingById<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        Awaited<ReturnType<typeof getTrainingById>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrainingById<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetTrainingById<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTrainingByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetTrainingByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTrainingByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrainingById>>> = ({
    signal,
  }) => getTrainingById(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getTrainingById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTrainingByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrainingById>>
>;
export type GetTrainingByIdSuspenseQueryError = ProblemDetails;

export function useGetTrainingByIdSuspense<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrainingByIdSuspense<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrainingByIdSuspense<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetTrainingByIdSuspense<
  TData = Awaited<ReturnType<typeof getTrainingById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTrainingById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTrainingByIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteTraining = (id: string) => {
  return customInstance<unknown>({
    url: `/api/trainings/${id}`,
    method: "DELETE",
  });
};

export const getDeleteTrainingMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTraining>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTraining>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteTraining"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTraining>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTraining(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTrainingMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTraining>>
>;

export type DeleteTrainingMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteTraining = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTraining>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTraining>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteTrainingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const findTrainingsForCalendar = (
  params: FindTrainingsForCalendarParams,
  signal?: AbortSignal,
) => {
  return customInstance<FindTrainingsForCalenderResponse>({
    url: `/api/trainings/Calendar`,
    method: "GET",
    params,
    signal,
  });
};

export const getFindTrainingsForCalendarQueryKey = (
  params?: FindTrainingsForCalendarParams,
) => {
  return [`/api/trainings/Calendar`, ...(params ? [params] : [])] as const;
};

export const getFindTrainingsForCalendarInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    FindTrainingsForCalendarParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsForCalendarParams["page"]
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsForCalendarQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    QueryKey,
    FindTrainingsForCalendarParams["page"]
  > = ({ signal, pageParam }) =>
      findTrainingsForCalendar(
        { ...params, page: pageParam || params?.["page"] },
        signal,
      );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData,
    QueryKey,
    FindTrainingsForCalendarParams["page"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsForCalendarInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarInfiniteQueryError = ProblemDetails;

export function useFindTrainingsForCalendarInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    FindTrainingsForCalendarParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsForCalendarParams["page"]
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendarInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    FindTrainingsForCalendarParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsForCalendarParams["page"]
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        QueryKey
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendarInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    FindTrainingsForCalendarParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsForCalendarParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainingsForCalendarInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    FindTrainingsForCalendarParams["page"]
  >,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData,
        QueryKey,
        FindTrainingsForCalendarParams["page"]
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsForCalendarInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsForCalendarQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsForCalendarQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>
  > = ({ signal }) => findTrainingsForCalendar(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsForCalendarQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarQueryError = ProblemDetails;

export function useFindTrainingsForCalendar<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        Awaited<ReturnType<typeof findTrainingsForCalendar>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendar<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        Awaited<ReturnType<typeof findTrainingsForCalendar>>
      >,
      "initialData"
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendar<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainingsForCalendar<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsForCalendarQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindTrainingsForCalendarSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindTrainingsForCalendarQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>
  > = ({ signal }) => findTrainingsForCalendar(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof findTrainingsForCalendar>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindTrainingsForCalendarSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof findTrainingsForCalendar>>
>;
export type FindTrainingsForCalendarSuspenseQueryError = ProblemDetails;

export function useFindTrainingsForCalendarSuspense<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendarSuspense<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindTrainingsForCalendarSuspense<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFindTrainingsForCalendarSuspense<
  TData = Awaited<ReturnType<typeof findTrainingsForCalendar>>,
  TError = ProblemDetails,
>(
  params: FindTrainingsForCalendarParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof findTrainingsForCalendar>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindTrainingsForCalendarSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTrainingSet = (
  id: string,
  createTrainingSetRequest: CreateTrainingSetRequest,
  signal?: AbortSignal,
) => {
  return customInstance<CreateTrainingSetResponse>({
    url: `/api/trainings/${id}/sets`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createTrainingSetRequest,
    signal,
  });
};

export const getCreateTrainingSetMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTrainingSet>>,
    TError,
    { id: string; data: CreateTrainingSetRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTrainingSet>>,
  TError,
  { id: string; data: CreateTrainingSetRequest },
  TContext
> => {
  const mutationKey = ["createTrainingSet"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTrainingSet>>,
    { id: string; data: CreateTrainingSetRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return createTrainingSet(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTrainingSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTrainingSet>>
>;
export type CreateTrainingSetMutationBody = CreateTrainingSetRequest;
export type CreateTrainingSetMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useCreateTrainingSet = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTrainingSet>>,
      TError,
      { id: string; data: CreateTrainingSetRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTrainingSet>>,
  TError,
  { id: string; data: CreateTrainingSetRequest },
  TContext
> => {
  const mutationOptions = getCreateTrainingSetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateTrainingSet = (
  id: string,
  updateTrainingSetRequest: UpdateTrainingSetRequest,
) => {
  return customInstance<UpdateTrainingSetResponse>({
    url: `/api/trainings/${id}/sets`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateTrainingSetRequest,
  });
};

export const getUpdateTrainingSetMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTrainingSet>>,
    TError,
    { id: string; data: UpdateTrainingSetRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTrainingSet>>,
  TError,
  { id: string; data: UpdateTrainingSetRequest },
  TContext
> => {
  const mutationKey = ["updateTrainingSet"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTrainingSet>>,
    { id: string; data: UpdateTrainingSetRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTrainingSet(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTrainingSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTrainingSet>>
>;
export type UpdateTrainingSetMutationBody = UpdateTrainingSetRequest;
export type UpdateTrainingSetMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useUpdateTrainingSet = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTrainingSet>>,
      TError,
      { id: string; data: UpdateTrainingSetRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTrainingSet>>,
  TError,
  { id: string; data: UpdateTrainingSetRequest },
  TContext
> => {
  const mutationOptions = getUpdateTrainingSetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteApiTrainingsIdSetsSetId = (id: string, setId: string) => {
  return customInstance<unknown>({
    url: `/api/trainings/${id}/sets/${setId}`,
    method: "DELETE",
  });
};

export const getDeleteApiTrainingsIdSetsSetIdMutationOptions = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
    TError,
    { id: string; setId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
  TError,
  { id: string; setId: string },
  TContext
> => {
  const mutationKey = ["deleteApiTrainingsIdSetsSetId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
    { id: string; setId: string }
  > = (props) => {
    const { id, setId } = props ?? {};

    return deleteApiTrainingsIdSetsSetId(id, setId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiTrainingsIdSetsSetIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>
>;

export type DeleteApiTrainingsIdSetsSetIdMutationError =
  | ProblemDetails
  | ValidationProblemDetails;

export const useDeleteApiTrainingsIdSetsSetId = <
  TError = ProblemDetails | ValidationProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
      TError,
      { id: string; setId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiTrainingsIdSetsSetId>>,
  TError,
  { id: string; setId: string },
  TContext
> => {
  const mutationOptions =
    getDeleteApiTrainingsIdSetsSetIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
